### ISSUE TITLE
Extract OpenapiClient to an sdk client gem

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-autosde#10]
It would be nice to extract the OpenapiClient to its own autosde_oas SDK gem

**Comment by gregoryb-at-ibm** [comment]
@agrare , Is this a blocker? Could we move this to a gem at a later stage? I'm concerned that we are making big changes, but we can't really do functional tests until we finish this initial round of PRs.

Also, I'm not familiar with what is an "SDK gem"? Do you have an example of such a thing? How is it different from a regular gem?

**Comment by agrare** [comment]
Not a blocker

**Comment by agrare** [comment]
@gregoryb-at-ibm what you have in `OpenapiClient` is an sdk gem, it has a [gemspec](https://github.com/Autosde/manageiq-providers-autosde/blob/master/app/models/manageiq/providers/autosde/storage_manager/openapi_client/generated/openapi_client.gemspec) and everything

https://github.com/aws/aws-sdk-ruby and https://github.com/vmware/rbvmomi/ are other examples of SDK gems, just a way of saying the library that talks to the provider's API

**Comment by borisko123** [comment]
@agrare this is closed by https://github.com/ManageIQ/manageiq-providers-autosde/pull/52
Can we close this issue?

**Comment by agrare** [comment]
:+1: yes
