### ISSUE TITLE
[Oparin] Kyndryl AutoSDE Provider Enhancements

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-autosde#136]
- [x] Validate storage button
  - [x] https://github.com/ManageIQ/manageiq-providers-autosde/pull/149
  - [x] https://github.com/ManageIQ/manageiq/pull/21882
  - [x] https://github.com/ManageIQ/manageiq-ui-classic/pull/8279
  - [x] https://github.com/ManageIQ/manageiq-api/pull/1163
- [x] Events Support
  - [x] Event Catcher https://github.com/ManageIQ/manageiq-providers-autosde/pull/151
  - [x] Link Physical Storages to events https://github.com/ManageIQ/manageiq-providers-autosde/pull/154 https://github.com/ManageIQ/manageiq/pull/22008
  - [x] Display events timeline for physical storages https://github.com/ManageIQ/manageiq-ui-classic/pull/8373
- [x] Service Catalog support https://github.com/ManageIQ/manageiq-providers-autosde/pull/157

Items completed in Najdorf Release: https://github.com/ManageIQ/manageiq-providers-autosde/issues/83

**Comment by agrare** [comment]
@llivne can you link any planned enhancements to this issue?

**Comment by llivne** [comment]
@ereztheodorou can you please update this issue with our planned enhancements, like @agrare asked us.

**Comment by agrare** [comment]
Marking this as complete in Oparin, we can add additional planned features in standalone issues going forward
