### ISSUE TITLE
collect storage service resource attachments

### ISSUE THREAD

**Issue by OrGur1987** [ManageIQ/manageiq-providers-autosde#202]
add the already existing model to the collection flow, so that `storage_services` would have a list of attached `storage_resources` and vice-versa:

![image](https://user-images.githubusercontent.com/106743023/217189172-85f73d73-b1b7-4530-b71b-8cbd9a4756a6.png)

PRs:
- [x] main repo: https://github.com/ManageIQ/manageiq/pull/22332
- [x] providers-autosde: https://github.com/ManageIQ/manageiq-providers-autosde/pull/203

**Comment by OrGur1987** [comment]
@agrare 
hi, I think the PR's in this issue are ready

**Comment by agrare** [comment]
All PRs are merged, closing
