### ISSUE TITLE
Cleanup redundant validate method from #58

### ISSUE THREAD

**Issue by gregoryb-at-ibm** [ManageIQ/manageiq-providers-autosde#61]
Cleanup redundant validate method in https://github.com/ManageIQ/manageiq-providers-autosde/pull/58

**Comment by chessbyte** [comment]
@gregoryb-at-ibm has this been addressed or still a to-do item?

**Comment by gregoryb-at-ibm** [comment]
@chessbyte , this hasn't been fixed. 
I'll bump it in our internal issue-tracker.

**Comment by gregoryb-at-ibm** [comment]
Closed by @chessbyte  at https://github.com/ManageIQ/manageiq-providers-autosde/pull/78
