### ISSUE TITLE
[MORPHY] IBM AutoSDE Provider Enhancements

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-autosde#82]
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/86
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/87
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/88
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/89
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/90
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/91
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/95
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/issues/96

**Comment by ereztheodorou** [comment]
SDE-1764 Define Roles for Client usage and L2 Usage
There are several capabilities that only a client can perform v/s actions only a L2 engineer can perform. This feature is created to define the roles and permissions required for each of the capability and action. For example, editing the storage volume can be done by Client but not by the L2, similarly the storage provider can be created by the L2 and not by Client himself/herself. 

SDE-1734 Ability to edit the Storage Device attributes
Currently, L2 engineer can only add a storage device in MIQ. There is no Option to Edit or modify the properties for the Storage Device once added. There must be an option to allow L2 engineer to modify the properties (lie password, IP address, host name etc) for the storage device.

SDE-1767 Ability to configure Volume for Expansion
Once a volume is created, users must be able to increase the size of the existing volume. When the user "edits" the volumes, the option to allow users to specify the size (GBs) to be expanded. We should display the current size allocated, "Size to Expand" along with the available storage capacity for users to expand the volume size.

SDE-1725 Validation Check for Chap_username and Chap_secret
If user enters CHAP Username or CHAP Secret, then the other filed must be mandatory (check needs to be done). (Currently both the values are optional in MIQ, if the user enters either of the value then both the values need to be provided.. Currently, no checks are done for validating both the values together.)

SDE-1736 Ability to create multiple Volumes in a single view/click
Most of the storage devices allow users to create multiple Volumes at the same point. Currently, MIQ only provides capability for users to create a single volume. If the user has the need to create 5 volumes, then user need to perform the operation 5 times.
It is necessary to have a feature to allow users to create multiple volumes in the same view.

**Comment by chessbyte** [comment]
@ereztheodorou I have created individual issues with the descriptions you provided above and linked them to this Release Epic Issue
